root = "."

tmp_dir = ".build"

[build]
args_bin = []
bin = ".build/main"
cmd = "go build -gcflags \"all=-N -l\" -o .build/main ./cmd/gql_server"
delay = 1000
exclude_dir = ["docker", "bin", "tools", ".build"]
exclude_file = ["*.md", "*.txt", "*.json"]
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec .build/main -- --update-interval ${CACHE_UPDATE_INTERVAL}"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
