// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type Location struct {
	// 地理情報の ID
	ID string `json:"id"`
	// 地理情報の名前
	Name string `json:"name"`
}

type Query struct {
}
